### ISSUE TITLE
运行评论情感分析demo报错

### ISSUE THREAD

**Issue by freestyledash** [AIChallenger/AI_Challenger_2018#24]
2018-10-24 07:58:03,091 [INFO] <MainProcess> (MainThread) start load data
2018-10-24 07:58:04,746 [INFO] <MainProcess> (MainThread) start seg train data
Building prefix dict from the default dictionary ...
2018-10-24 07:58:04,747 [DEBUG] <MainProcess> (MainThread) Building prefix dict from the default dictionary ...
Loading model from cache c:\users\user\appdata\local\temp\jieba.cache
2018-10-24 07:58:04,750 [DEBUG] <MainProcess> (MainThread) Loading model from cache c:\users\user\appdata\local\temp\jieba.cache
Loading model cost 0.344 seconds.
2018-10-24 07:58:05,092 [DEBUG] <MainProcess> (MainThread) Loading model cost 0.344 seconds.
Prefix dict has been built succesfully.
2018-10-24 07:58:05,092 [DEBUG] <MainProcess> (MainThread) Prefix dict has been built succesfully.
2018-10-24 08:02:45,384 [INFO] <MainProcess> (MainThread) complete seg train data
2018-10-24 08:02:45,384 [INFO] <MainProcess> (MainThread) start train feature extraction
Traceback (most recent call last):
  File "D:/work/SentimentanalysisCore-master/Baselines/main_train.py", line 52, in <module>
    vectorizer_tfidf.fit(content_train)
  File "C:\Python27\lib\site-packages\sklearn\feature_extraction\text.py", line 1562, in fit
    X = super(TfidfVectorizer, self).fit_transform(raw_documents)
  File "C:\Python27\lib\site-packages\sklearn\feature_extraction\text.py", line 1012, in fit_transform
    self.fixed_vocabulary_)
  File "C:\Python27\lib\site-packages\sklearn\feature_extraction\text.py", line 934, in _count_vocab
    values.extend(feature_counter.values())
MemoryError

**Comment by freestyledash** [comment]
依赖已经按照
python==2.7.13
numpy==1.13.1
pandas==0.20.3
jieba==0.39
sklearn==0.19.2
正确安装了

**Comment by freestyledash** [comment]
mac 上运行好使，windows有些问题，放弃windows
